- cloudstack/cloudstack.yaml
When run 
cfy local install-plugins -p cloudify-manager-blueprints/cloudstack/cloudstack.yaml
It will fail with the error:
Failed on import - Unable to open import url https://raw.githubusercontent.com/cloudify-cosmo/cloudify-cloudstack-plugin/master/plugin.yaml.template;
I corrected the import.
> Fixed invalid import

- cloudstack/cloudstack.yaml
Tested against 3.2 m5 release and everything seems ok, so bumping version on master.
> Bump to 3.2m5 / 1.2m5

- components/elasticsearch/scripts/create.py
- components/rabbitmq/scripts/create.py
Reverts cloudify-cosmo/cloudify-manager-blueprints#264
> Revert "CFY-5117 now correctly passing external rabbitmq endpoint"

- components/elasticsearch/scripts/create.py
There's no "deploy_blueprint_resource" equivalent for directories,
so we need to copy each script file separately (fortunately, there's
just one right now).
Further work might involve adding a method to copy a directory.
> ES create: copy scripts one-by-one

- aws-ec2-manager-blueprint-inputs.yaml
use_existing_manager_keypair and use_existing_agent_keypair are defined as boolean keys in the ec2 blueprint and therefore should have boolean values as inputs
the ssh_key_filename and agent_private_key_path values were somehow mixed with the values of use_existing_manager_keypair and use_existing_agent_keypair
> updated ec2 manager blueprint inputs to match their blueprint key type

- components/rabbitmq/scripts/start.py
- components/utils.py
Turns out sometimes `rabbitmqctl status` can return active a bit before
rabbitmq actually starts listening. Let's retry the port accessibility
checking.
> RabbitMQ start script: add retry to verifying if the port is open.

- components/nginx/scripts/start.py
- components/restservice/scripts/start.py
- components/utils.py
The endpoint we're using to check if the REST service is working
is unavailable in maintenance mode (so, when upgrading the manager).
Bypass the maintenance mode for that request.
> CFY-5255 REST service sanity check: bypass maintenance

- simple-manager-blueprint.yaml
- types/manager-types.yaml
The upgrade validation scripts need to be uploaded to the target host,
so only do that in the simple blueprint, which requires having a
machine running.
The simple manager blueprint is the one that's used for upgrades
typically, anyway.
> CFY-4953 Move validation scripts to the simple manager blueprint

- aws-ec2-manager-blueprint.yaml
- components/utils.py
- openstack-manager-blueprint.yaml
- simple-manager-blueprint.yaml
- types/manager-types.yaml
- vcloud-manager-blueprint.yaml
- vsphere-manager-blueprint.yaml
The yum_install function only handled .rpm files correctly. This
change also makes it handle repository packages, eg. "python-devel".
This is required so that the `install_python_compilers` flag can work.
Also changed the `install_python_compilers` flag to be a boolean.
> CFY-5384 utils.yum_install: don't break on repository packages

- components/rabbitmq/config/cloudify-rabbitmq
- components/rabbitmq/config/cloudify-rabbitmq.service
- components/rabbitmq/config/kill-rabbit
- components/rabbitmq/scripts/create.py
The systemd unit for rabbitmq uses commands that start and stop rabbit
in a blocking fashion - it is started/stopped before the script
returns. This is required for correct interop with systemd.
> CFY-5469 Use `rabbitmqctl stop` in systemd ExecStop

- components/manager/scripts/creation_validation.py
- components/rabbitmq/scripts/creation_validation.py
- 'ssl' is not a separate property, it's nested under 'security'
- rabbitmq cert properties are rabbitmq_cert_*, not broker_cert_path
> CFY-4953 Preupgrade validation fixups

- components/mgmtworker/config/cloudify-mgmtworker.service
- components/restservice/config/cloudify-restservice.service
In addition, removed the `PIDFile` entry from the gunicorn unit file as
it has no effect since the `Type` entry defaults to `simple`.
> CFY-5698 Remove `--pidfile` argument from the celery call in its unit file

- components/restservice/scripts/start.py
Catching only URLError will also catch HTTPError, which would stop
execution from ever reaching the lines that check the response code.
Make sure to continue on HTTPError.
> restservice/start.py sanity check: use URLError correctly

- aws-ec2-manager-blueprint.yaml
- azure-manager-blueprint.yaml
- components/consul/scripts/create.py
- components/keepalived/scripts/create.py
- components/postgresql/scripts/create.py
- components/syncthing/scripts/create.py
- inputs/manager-inputs.yaml
- openstack-manager-blueprint.yaml
- simple-manager-blueprint.yaml
- types/manager-types.yaml
- vcloud-manager-blueprint.yaml
- vsphere-manager-blueprint.yaml
Install all the required packages. Don't configure them yet, configuration will be
on demand, enabled on an already running manager.
This just makes sure all the packages are there.
> CFY-6000 Install components required by the manager HA cluster

- aws-ec2-manager-blueprint-inputs.yaml
- azure-manager-blueprint-inputs.yaml
- components/restservice/config/cloudify-restservice.service
- components/restservice/scripts/configure.py
- inputs/manager-inputs.yaml
- openstack-manager-blueprint-inputs.yaml
- simple-manager-blueprint-inputs.yaml
- tests/unit-tests/test_restservice.py
- types/manager-types.yaml
- vcloud-manager-blueprint-inputs.yaml
- vsphere-manager-blueprint-inputs.yaml
In this PR, a new property is added to `manager.nodes.RestService` called `gunicorn_worker_count` that can be used to configure how many worker nodes should be used to handle requests. This property by default gets its value from the `rest_service_gunicorn_worker_count` input which has been added to the inputs files under the *REST configuration* section with a default value of `0`.
The property value is used in the context passed to the template to render the `cloudify-restservice.service` systemd file that is used to launch the rest service. In particular, it's used to set the value of the `-w` option that sets the number of worker processes that will be used. The logic in the template is as follows:
- For a falsy value (0): it will render the the old default of `$(($(nproc)*2+1))`
- …
> CFY-6070. Configure rest service worker count

- components/logstash/scripts/create.py
- components/utils.py
In this PR, the target directory for the jdbc driver file is created before curl is executed to workaround the permissions error.
> CFY-6090. Fix download error

- components/logstash/scripts/create.py
This should fix permission problems when running `curl` as some user different from `root` and `logstash`.
> CFY-6090. Download to temp directory and copy as logstash user

- components/logstash/config/logstash.conf
- components/logstash/scripts/create.py
- inputs/manager-inputs.yaml
In this PR, the schema for the `logs` and `events` tables has been updated to include the same fields as seen in the elasticsearch records except for those fields that don't really add any information:
- `tags` is used by logstash to decide in which table to insert each record
- `type` is always set to `cloudify_log` for logs and `cloudify_event` for events
There are still a few fields that don't seem to be used that might be removed in the future:
- `message_code` seems to be always set to `null`
- `message.argument` seems to be always set to `null` (only present for events)
Even, a change in the schema might be useful to display information in a clearer way. For example, using a `message` field directly would make it easier to use instead of having a json object that contains a  `text` …
> CFY-6133. Store json data for logs/events in PostgreSQL

- components/logstash/config/logstash.conf
- components/logstash/scripts/create.py
In this PR:
- a new column named `message_vector` of type `tsvector` is added to the `logs` and `events` tables to store the parsed version of the message
- an index on that `message_vector` column is created
After these changes, full-text search queries against the `logs` and `events` tables can be executed efficiently. For example: `SELECT message FROM logs WHERE message_vector @@ to_tsquery('server')`.
Note that, after the bootstrap process, some messages contains fragments surrounded by `<`  and `>` signs such as:
`Applying function:setter on Attribute <file_server_port>`
The problem with those fragments is that the parser confuses them with XML tags and discards them. To include them in the vector, the `translate` function is used to drop the `<` and `>` characters as suggested in …
> CFY-6133. PostgreSQL full-text search

- components/logstash/config/logstash.conf
- components/logstash/scripts/create.py
In this PR, the code that creates the `logs` and `events` tables is removed since those tables will be created based on a model defined in the rest service code.
Related: cloudify-cosmo/cloudify-manager#638
> CFY-6091. Create log tables in rest service

- aws-ec2-manager-blueprint-inputs.yaml
- azure-manager-blueprint-inputs.yaml
- components/restservice/config/cloudify-restservice
- components/restservice/config/cloudify-restservice.service
- inputs/manager-inputs.yaml
- openstack-manager-blueprint-inputs.yaml
- simple-manager-blueprint-inputs.yaml
- tests/unit-tests/test_restservice.py
- types/manager-types.yaml
- vcloud-manager-blueprint-inputs.yaml
- vsphere-manager-blueprint-inputs.yaml
The default number of gunicorn workers (cpus*2 + 1) should have an upper bound limit as in VMs with many CPUs this can turn to a memory issue and probably not necessary to have that many gunicorn workers.
In this PR, the number of gunicorn workers is limited to 12.
The ability to configure the number of workers is preserved.
> CFY-6161 set an upper bound limit (12) for gunicorn number of workers

- aws-ec2-manager-blueprint-inputs.yaml
- aws-ec2-manager-blueprint.yaml
- azure-manager-blueprint.yaml
- components/restservice/config/cloudify-restservice
- components/restservice/config/cloudify-restservice.service
- components/restservice/scripts/preconfigure.py
- openstack-manager-blueprint-inputs.yaml
- openstack-manager-blueprint.yaml
- simple-manager-blueprint-inputs.yaml
- simple-manager-blueprint.yaml
- tests/unit-tests/test_restservice.py
- types/manager-types.yaml
- vcloud-manager-blueprint-inputs.yaml
- vcloud-manager-blueprint.yaml
- vsphere-manager-blueprint-inputs.yaml
- vsphere-manager-blueprint.yaml
This PR is for 3.4.1:
1. Configurable gunicorn worker count.
2. Upper bound limit (12) if gunicorn worker count is auto calculated.
> CFY-6161 make number of gunicorn workers configurable and limited to 12

- aws-ec2-manager-blueprint-inputs.yaml
- components/restservice/config/cloudify-restservice.service
- inputs/manager-inputs.yaml
- openstack-manager-blueprint-inputs.yaml
- simple-manager-blueprint-inputs.yaml
- tests/unit-tests/test_restservice.py
- types/manager-types.yaml
- vcloud-manager-blueprint-inputs.yaml
- vsphere-manager-blueprint-inputs.yaml
In this PR, gunicorn max requests is set to 1000 and is configurable using an input.
In addition, the gunicorn worker count input format has been adjusted as it was in TOSCA format while inputs are just yaml files with keys and values.
> CFY-6163 gunicorn max requests = 1000 and configurable

- aws-ec2-manager-blueprint-inputs.yaml
- aws-ec2-manager-blueprint.yaml
- azure-manager-blueprint.yaml
- components/restservice/config/cloudify-restservice.service
- openstack-manager-blueprint-inputs.yaml
- openstack-manager-blueprint.yaml
- simple-manager-blueprint-inputs.yaml
- simple-manager-blueprint.yaml
- tests/unit-tests/test_restservice.py
- types/manager-types.yaml
- vcloud-manager-blueprint-inputs.yaml
- vcloud-manager-blueprint.yaml
- vsphere-manager-blueprint-inputs.yaml
- vsphere-manager-blueprint.yaml
In this PR an input is added for setting gunicorn max requests setting where the default value is 1000.
> CFY-6163 set gunicorn max requests to 1000 and make it configurable

- components/manager/scripts/sanity/sanity.py
The latest update in the restservice is more restrictive in terms of parameters that are needed. In this change, the parameters that are missing have been added.
Note: this is just a quick fix, better validation should be implemented in the rest service method in the future.
> CFY-6091 Fix sanity check by updating parameters in event URL

- components/restservice/config/cloudify-rest.conf
- components/restservice/config/create_tables_and_add_users.py
- Make the default tenant ID constant (set to 0)
- Prevent deletion of the default tenant
- Streamline the creation of the default tenant
- Make more use of the default tenant constants (instead of strings)
> CFY-6317 Protect default tenant

- .travis.yml
- circle.yml
- components/logstash/config/logstash.conf
In this PR, logstash configuration is updated to insert `node_id` and `operation` values into the `events`/`logs` tables in the database. If any of these values is missing then `NULL` is inserted instead.
Requires: cloudify-cosmo/cloudify-manager#699
> CFY 6090. Add missing columns to events

- aws-ec2-manager-blueprint.yaml
- azure-manager-blueprint.yaml
- openstack-manager-blueprint.yaml
We can't guarantee a private network between all cluster nodes
currently - allow 0.0.0.0/0 access to them.
> CFY-6373 Security groups: allow world access to cluster ports

- components/manager-ip-setter/scripts/create-internal-ssl-certs.py
- components/manager-ip-setter/scripts/create.py
- components/manager-ip-setter/scripts/manager-ip-setter.sh
- components/nginx/config/https-internal-rest-server.cloudify
In this PR, the manager-ip-setter service is updated to generate the internal SSL certificates when booting the manager from an image.
In order to achieve that, the utils.generate_internal_ssl_cert function is used.
> CFY-6497 generate internal SSL certificates on boot

- aws-ec2-manager-blueprint.yaml
- azure-manager-blueprint.yaml
- components/manager-ip-setter/node-template.yaml
- openstack-manager-blueprint.yaml
- simple-manager-blueprint.yaml
- vcloud-manager-blueprint.yaml
- vsphere-manager-blueprint.yaml
Every node that uses fabric (for .py scripts) needs to have a
depends_on relationship to the manager_configuration, because that's
where the host_string is taken from, for the fabric env.
(the relationship can be directly to manager_configuration, or
to some other node that depends on it)
Without this change, some nodes can be created before
manager_configuration, which will lead to an empty host_string in
their fabric inputs, and an error message from fabric.
> CFY-6576 Make IPSetter and stage depend on manager_configuration

- components/logstash/config/logstash.conf
In this PR, logstash configuration is updated to insert the error causes field into the events table if available.
Depends: cloudify-cosmo/cloudify-manager#799
> CFY-6479 Insert error causes value into the events table

- components/logstash/config/logstash.conf
The insert queries for new events/logs have been updated to use the timestamp provided by the event data structure to set the `reported_timestamp` field instead of the `timestamp` one. Now, `timestamp` will be populated automatically by the database using the current timestamp.
> CFY-6647 Set reported_timestamp when new event/log is inserted

- components/logstash/config/logstash.conf
In this PR, the logstash configuration is updated to include the `_tenant_id` and `_creator_id` fields in the event and log insert queries. This is because these fields are now part of both tables while in the past they where retrieved through an association proxy.
> CFY-6660. Include _tenant_id and _created_id in event/log insert queries

- components/logstash/config/logstash.conf
In this PR, the logstash insert queries have been updated to use just a single subquery since all the subqueries were used to extract information from the same execution.
> CFY-6660 Update insert queries to use one subquery

- components/logstash/config/logstash.conf
- components/logstash/scripts/create.py
In this PR, the `error_causes` object is stored as a json-encode string in the `events` table.
To make this happen, the `logstash-filter-json_encode` plugin is installed and the logstash configuration is updated.
Note: the plugin is installed directly from the internet. When the resources file is updated with the `gem` file for the plugin, the installation function should be updated accordingly.
> CFY 6479. Serialize error causes

- components/restservice/config/cloudify-restservice.service
The REST service uses DBus for the status endpoint, which makes DBus
a requirement for running the REST Service. Add the DBus service as
a 'Wants' in the REST unit file so that it is started if needed.
> CFY-6720 Add `Wants=dbus.service` to cloudify-restservice

- components/logstash/scripts/create.py
- inputs/manager-inputs.yaml
- types/manager-types.yaml
In this PR, the changes needed to install the `logstash-filter-json_encode` plugin from the cloudify manager resources file have been made.
The resources file change is in progress, so the PR will be merged only after the resources file has been updated.
> CFY 6479. Install logstash plugin from resources file

- components/restservice/scripts/configure.py
- components/restservice/scripts/preconfigure.py
After cloudify-cosmo/cloudify-plugins-common#320 it is not necessary
to jsonify by hand, as dicts/lists in runtime props will be handled
correctly in fabric-plugin scripts
> CFY-6740 Don't jsonify restservice security_configuration

- components/logstash/scripts/create.py
This PR is a quick fix to use `rngd` to feed `/dev/random` from `/dev/urandom`.
This way logstash plugin installation doesn't stall because of lack of entropy
> CFY-6745 Use rngd to feed /dev/random from /dev/urandom

- components/logstash/scripts/create.py
In this PR, `/dev/urandom` is used as entropy gathering device when installing logstash plugins.
Supersedes: #550
> CFY 6745. Use /dev/urandom when installing plugins

- components/postgresql/scripts/start.py
It seems it might be a race condition to only `.flush()`, and then `move()` (since move uses a separate `mv` process?)
Observed behaviour was, the `/root/.pgpass` file was empty after bootstrap (seems very rare)
> postgresql .pgpass: only move after closing the file

- components/utils.py
This fixes passing an url as eg. the rest_service_source_url input.
When a url is passed there, there's no point in looking for it
on disk - it needs to be downloaded
> Don't use get_filepath_from_pkg_name for urls

- components/logstash/config/logstash.conf
In this PR, logstash configuration is updated to insert explicitly a timestamp value in UTC.
This is because there is no longer a default value for the events/logs tables at the database level. Hence, logstash must provide the value on its own and make sure that is in UTC.
Related: cloudify-cosmo/cloudify-manager#894
> CFY-7005. Insert timestamp explicitly in logstash events/logs

- inputs/manager-inputs.yaml
- simple-manager-blueprint.yaml
This input will be set in `cloudify.cloudify_agent.networks`,
and subsequently in the provider context.
> CFY-7200 Add a `manager_networks` bootstrap input

- components/manager-ip-setter/config/cloudify-manager-ip-setter.service
- components/manager-ip-setter/scripts/manager-ip-setter.sh
- components/manager-ip-setter/scripts/update-provider-context.py
Instead of using the REST API to update provider context, simply use
restservice's storage_manager directly - this makes it faster, and avoids
a circular dependency issue (where restservice needs to be started for
ipsetter to work, but without ipsetter, restservice is using the wrong cert)
> CFY-7215 Use storage_manager directly in ipsetter

- components/manager-ip-setter/config/cloudify-manager-ip-setter.service
If we don't declare that the IPSetter must run after network-online,
it might be run before networks have been set up, and then it won't
find the server IP and will fail.
This change makes it run after network-online, so the IP will be
found correctly.
> CFY-7215 Run IPSetter after the network is online

- components/manager-ip-setter/config/cloudify-manager-ip-setter.service
For type=oneshot services, the services depended on it, will wait for
the oneshot service to finish before they run.
Without this, IPSetter is the default "simple" type, which means that
nginx might start running BEFORE ipsetter finishes, and then nginx
will be using the old certificate, before it was replaced.
> CFY-7215 Use Type=oneshot for IPSetter

- components/amqpinflux/scripts/create.py
- components/manager-ip-setter/scripts/create-internal-ssl-certs.py
- components/manager-ip-setter/scripts/create.py
- components/manager/scripts/configure_manager.py
- components/manager/scripts/set_manager_ips.py
- components/mgmtworker/scripts/create.py
- components/nginx/scripts/preconfigure.py
- components/rabbitmq/config/rabbitmq.config
- components/restservice/scripts/create.py
- components/utils.py
- simple-manager-blueprint.yaml
This also handles CFY-7191 (sign the new certs using the CA certs).
Instead of creating just an internal cert, and using that for everything,
we now separately create a CA cert, which is used (by the manager,
and by the agents) to verify connections, and an internal cert, which
is used by the servers.
This also contains several seemingly unrelated changes that were
required to do this sanely (but increase the overall quality IMO!),
so ideally go commit-by-commit while reviewing this.
> CFY-7190 Use a separate CA cert

- components/manager-ip-setter/scripts/create-internal-ssl-certs.py
- components/manager-ip-setter/scripts/create.py
This allows using the script from ipsetter to re-create the internal cert with
the current CA, after the CA has been replicated from a cluster master,
after a join to a cluster.
> CFY-7220 A way to recreate the certs with the current CA

- components/manager/scripts/configure_manager.py
- components/nginx/scripts/preconfigure.py
Not all environments come with openssl preinstalled, and openssl is
only installed via nginx. Only after that can we create the certs.
For now, simply move the cert creation code to after openssl is
installed. In the future, let's install openssl explicitly and revert
this commit.
> Create the certs in nginx's create.py script

- components/utils.py
Instead, it should keep being self-signed.
> CFY-7190 The external cert should not use the internal CA

- components/manager-ip-setter/scripts/create-internal-ssl-certs.py
When the IP changes, we update the default network with the new ip
in the provider context. we also need to update the cert metadata
file as well.
> CFY-7200 IPSetter: update the default network in cert metadata

- components/restservice/scripts/create.py
- components/restservice/scripts/set-manager-ssl.py
Instead of calling `sed` from the restservice code, let's add
a script that will do the necessary config changes.
This way, we can also run that script from within cluster code,
and also we won't need to enable `sudo` for `sed`, only for this
specific script.
> CFY-7188 Add a script to set manager SSL state

- components/nginx/scripts/start.py
We can't easily use python's urllib there, because we would need
to keep compatibility between python versions that do https
cert verification (2.7.9+, and 2.7.5 with centos patches starting from
2.7.5-58), and ones that don't.
Instead, we use curl, because it behaves consistently across distro
versions.
> CFY-7222 Use curl for the nginx check

- components/mgmtworker/scripts/create.py
- components/sanity/scripts/start.py
- types/manager-types.yaml
The direct reason for this change is that new centos/rhel ship
a patched python version (2.7.5-58) that contains python 2.7.9's
SSL patches, and will start verifying certificates by default with
urllib2.
Keeping backwards compatibility with earlier versions that didn't
verify certificates means we can't keep using urllib2 for this, but
instead should use something that verifies the certificate on
both the new and the old versions, like requests.
For that, we can simply use cloudify-rest-client, which is already
installed in the mgmtworker env.
Using the REST client is arguably also much cleaner than raw
urllib2 calls.
> CFY-7222 Use cloudify-rest-client for the sanity check

- components/sanity/scripts/start.py
_is_sanity_blueprint_exist should of course check for blueprints,
not for deployments
> CFY-7222 Sanity: fix mistyped call

- components/sanity/scripts/postconfigure.py
- components/sanity/scripts/start.py
- types/manager-types.yaml
Otherwise we'd be requiring 127.0.0.1 in the external cert.
> CFY-5854 Use internal communication for the sanity check

- components/mgmtworker/config/cloudify-mgmtworker
This will allow to set a different path for the `authorization.conf`
file if needed during bootstrap.
> CFY-7240 Add authorization.conf path to environment variable

- components/nginx/scripts/create.py
- components/nginx/scripts/preconfigure.py
- components/utils.py
- inputs/manager-inputs.yaml
- types/manager-types.yaml
This adds the inputs `ca_certificate`, `ca_key`, `internal_certificate` and `internal_key`.
The user can now pass the internal CA cert+key, and the internal cert+key.
Optionally, the user can choose to not provide the CA key, but only the cert.
In this case, it is required that the user also provides the internal cert+key,
because they can't be generated without a CA key.
This means it is now possible to generate all the required certificates before
bootstrapping a manager, and cloudify does not require the CA key that was
used to generate the keys.
> CFY-7236 Allow passing internal certs in inputs

- components/nginx/scripts/preconfigure.py
Either both the key and the cert must be provided, or neither. It is
an error to only provide one of them. Add a check that throws an
exception in this case.
> CFY-7236 Add a check for user-provided internal key + cert

- components/restservice/config/authorization.conf
This action is used to update the user-tenant relationship. For now,
that means updating the role.
> CFY-7350. Add tenant_update_user action

- components/restservice/config/authorization.conf
This action is used to update the group-tenant relationship. For now,
that means updating the role.
> CFY-7373 Add tenant_update_group action

- components/python/scripts/create.py
Backports & setuptools are prerequisites for pip.
> CFY-7423: fix order of RPM installation

- components/postgresql/config/create_default_db.sh
In cases where trying several times to bootstrap the manager, this will
fix the problem of trying to drop a user that has tables associated with
him
> CFY-7485 Drop Stage and Composer tables before trying to drop the user
