aws-ec2/scripts/configure.py

But because the issue with the version tool it was delayed and forgotten. Now it is remembered

The Configure Script should have been merged

---

new/components/elasticsearch/scripts/create.sh
new/components/java/scripts/create.sh
new/components/logstash/config/logstash
new/components/logstash/scripts/create.sh
new/components/nginx/config/nginx.conf
new/components/nginx/scripts/create.sh
new/components/rabbitmq/scripts/create.sh
new/components/riemann/scripts/create.sh
new/components/utils

Ensures all manager logs end up in /var/log/cloudify

CFY-3023-better-log-locations

---

new/components/utils

This will fix date formatting to not include spaces.

CFY-3970 fix date formating

---

aws-ec2-RHEL-manager-blueprint-inputs.yaml
aws-ec2-manager-blueprint-inputs.yaml
aws-ec2-manager-blueprint.yaml

providing defaults and notes plus commenting out defaults with values

---

vcloud-manager-blueprint-inputs.yaml
vcloud-manager-blueprint.yaml
vsphere-manager-blueprint-inputs.yaml
vsphere-manager-blueprint.yaml

Add additional inputs descriptions for vsphere
Add input for support token based login for private vcloud (vcloud_org_url)

cleanup inputs for vsphere and add private vcloud input

---

components/elasticsearch/scripts/start.py
components/influxdb/scripts/start.py
components/java/scripts/validate.py
components/logstash/scripts/start.py
components/mgmtworker/scripts/start.py
components/nginx/scripts/start.py
components/python/scripts/validate.py
components/rabbitmq/scripts/start.py
components/restservice/scripts/start.py
components/utils.py
types/manager-types.yaml

Perform basic sanity checks in each node's start script, verifying
that the services started correctly.

CFY-5255 Perform basic sanity checks after starting each node

---

components/amqpinflux/scripts/creation_validation.py
components/elasticsearch/scripts/creation_validation.py
components/influxdb/scripts/creation_validation.py
components/logstash/scripts/creation_validation.py
components/manager/scripts/creation_validation.py
components/mgmtworker/scripts/creation_validation.py
components/nginx/scripts/creation_validation.py
components/nginx/scripts/start.py
components/rabbitmq/scripts/creation_validation.py
components/restservice/scripts/creation_validation.py
components/riemann/scripts/creation_validation.py
components/utils.py
tests/unit-tests/test_upgrade.py
types/manager-types.yaml

Add validation scripts to run before a manager upgrade,
checking that the required services are running, that the
directory structure looks as expected, and that some
properties didn't change.

CFY-4953 Pre-upgrade validations

---

aws-ec2-manager-blueprint-inputs.yaml
aws-ec2-manager-blueprint.yaml
components/manager/scripts/create.py
openstack-manager-blueprint-inputs.yaml
openstack-manager-blueprint.yaml
simple-manager-blueprint-inputs.yaml
simple-manager-blueprint.yaml
vcloud-manager-blueprint-inputs.yaml
vcloud-manager-blueprint.yaml
vsphere-manager-blueprint-inputs.yaml
vsphere-manager-blueprint.yaml

Reverts cloudify-cosmo/cloudify-manager-blueprints#325

Revert "CFY-5004 remove plugins resources"

---

aws-ec2-manager-blueprint-inputs.yaml
aws-ec2-manager-blueprint.yaml
components/manager/scripts/create.py
openstack-manager-blueprint-inputs.yaml
openstack-manager-blueprint.yaml
simple-manager-blueprint-inputs.yaml
simple-manager-blueprint.yaml
vcloud-manager-blueprint-inputs.yaml
vcloud-manager-blueprint.yaml
vsphere-manager-blueprint-inputs.yaml
vsphere-manager-blueprint.yaml

Reverts cloudify-cosmo/cloudify-manager-blueprints#330

Revert "Revert "CFY-5004 remove plugins resources""

---

aws-ec2-manager-blueprint.yaml
azure-manager-blueprint-inputs.yaml
azure-manager-blueprint.yaml
components/manager/scripts/azure/configure.py

Support Azure Manager Blueprint

Cfy 5203 v1.4

---

components/elasticsearch/scripts/creation_validation.py
components/logstash/scripts/creation_validation.py
components/nginx/scripts/creation_validation.py
components/rabbitmq/scripts/creation_validation.py

- Typo in rabbitmq
- Nginx & logstash swapped
- elasticsearch validates the directories before using them

CFY-4953 Pre-upgrade validation fixes.

---

components/utils.py
types/manager-types.yaml

CFY-5598 Change the format of how agent rest credentials are stored.

---

components/restservice/config/cloudify-restservice
components/restservice/config/create_tables_and_add_users.py
components/restservice/scripts/configure.py
components/restservice/scripts/create.py
components/restservice/scripts/preconfigure.py

- Keep them in the flask app config (taken from rest-security.conf)
- Update unittests/integration tests accordingly

CFY-6319 Generate random hash_salt and secret key during bootstrap

---

components/utils.py

Added `file` URL and also added `://` to all prefixes.

CFY-6498: fix to support file:// URLs

---

components/manager-ip-setter/config/cloudify-manager-ip-setter.service
components/manager-ip-setter/scripts/create-internal-ssl-certs.py
components/manager-ip-setter/scripts/create.py
components/manager-ip-setter/scripts/manager-ip-setter.sh
components/manager/scripts/disable_requiretty.sh
components/mgmtworker/config/cloudify-mgmtworker.service
components/mgmtworker/scripts/configure.py
components/mgmtworker/scripts/create.py
components/rabbitmq/config/rabbitmq-env.conf
components/rabbitmq/scripts/create.py
components/utils.py
types/manager-types.yaml

Mgmtworker and manager IP setter
Includes some changes to improve IP setter.

Cfy 6734+6736 non root components

---

components/mgmtworker/scripts/create.py
components/riemann/config/cloudify-riemann.service
components/riemann/scripts/configure.py
components/riemann/scripts/create.py
simple-manager-blueprint.yaml
types/manager-types.yaml

Not to be merged until docl tests done (comment will be added to note this).

CFY-6737- Run riemann as non-root

---

components/mgmtworker/scripts/configure.py
components/mgmtworker/scripts/create.py
components/mgmtworker/scripts/snapshot_permissions_fixer
components/postgresql/scripts/start.py
components/restservice/scripts/configure.py
components/utils.py
simple-manager-blueprint.yaml
types/manager-types.yaml

Also requires system workflows change- PR on the way.

Fix snapshot permissions

---

README.md

Update the docs link in README

---

components/nginx/config/rest-location.cloudify
components/nginx/scripts/preconfigure.py
components/restservice/scripts/create.py

deploy or generate external certificate even if ssl is disabled
add ssl to api in nginx
allow cfyuser to run sed command

CFY-7119 allow enabling and disabling of ssl after bootstrap

---

components/manager-ip-setter/scripts/update-provider-context.py

In addition to updating the broker IP

CFY-7197 Update the default network in the provider context (IP setter)

---

components/restservice/config/authorization.conf

CFY-7408 allow user with default role to list tenants

CFY-7408 fix permissions in authorization.config

---

inputs/manager-inputs.yaml

@mcouthon you should probably update the new RPM-based installer accordingly...

CFY-7645: add https prefixes
